using DG.Tweening;
using System.Collections;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;

public class CatScript : MonoBehaviour
{
    public float pushForce = 10.0f; // ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Î‚ï¿½ï¿½Í‚Ì‘å‚«ï¿½ï¿½
    public enum Mode
    {
        Scan,
        Chase,
        Hikkaku,
        Kuwaeru,

    }
    public Mode mode = Mode.Scan;
    [SerializeField] float distance;
    [SerializeField] Vector2 childPos;
    [SerializeField] GameObject target;
    public string TargetTag = "Player";
    SpriteRenderer spriteRenderer;
    [SerializeField] Vector3 easePos;
    bool isEase;
    public Vector2 direction_;
    GameObject player;
    public bool isAttack;
    [SerializeField] bool kuwaeru;
    public Transform closestChild;
    float BakuBakuTime = kBakuBakuTime;
    const float kBakuBakuTime = 5.0f;
    float chaseCoolTime;
    const float kchaseCoolTime = 3.0f;
    [SerializeField] bool onDanbol;

    Animator anim;
    private Vector3 prePos;
    private bool canFlip = true;

    // ï¿½Jï¿½ï¿½ï¿½ï¿½
    private GameObject cameraObj;
    private ScrollManager scrollManager;
    private float halfWidth;
    // ï¿½Jï¿½ï¿½ï¿½ï¿½ï¿½Ì’ï¿½ï¿½É“ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½tï¿½ï¿½ï¿½O
    private bool isEnterCamera;

    // ï¿½Qï¿½[ï¿½ï¿½ï¿½Jï¿½nï¿½Ç—ï¿½ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½g
    [SerializeField] private GameObject gameFlagObj;
    private GameFlagManager gameFlagManager;

    //[SerializeField] float distance;
    // Start is called before the first frame update
    void Start()
    {
        spriteRenderer = GetComponent<SpriteRenderer>();
        anim = GetComponent<Animator>();
        halfWidth = Camera.main.ScreenToWorldPoint(new(Screen.width, 0f, 0f)).x;
        cameraObj = GameObject.FindGameObjectWithTag("MainCamera");
        scrollManager = cameraObj.GetComponent<ScrollManager>();
        isEnterCamera = false;
        gameFlagManager = gameFlagObj.GetComponent<GameFlagManager>();
    }
    // Update is called once per frame
    void Update()
    {
        if (isEnterCamera && gameFlagManager.GetIsStart())
        {
            if (direction_.x > 0)
            {
                if (kuwaeru)
                {
                    spriteRenderer.flipX = false;
                }
                else
                {
                    spriteRenderer.flipX = true;
                }
                direction_.x = 1.0f;
            }
            else
            {
                if (kuwaeru)
                {
                    spriteRenderer.flipX = true;
                }
                else
                {
                    spriteRenderer.flipX = false;

                }
                direction_.x = -1.0f;
            }
            if (target != null)
            {
                distance = Vector2.Distance(transform.position, target.transform.position);
                direction_ = target.transform.position - transform.position;
                direction_.Normalize();

            }

            switch (mode)
            {
                case Mode.Scan:
                    if (chaseCoolTime > 0)
                    {
                        chaseCoolTime -= Time.deltaTime;
                    }
                    // ï¿½Qï¿½[ï¿½ï¿½ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½ÌˆÊ’uï¿½ğ’†Sï¿½ÉAï¿½ï¿½ï¿½a5ï¿½Ì”ÍˆÍ“ï¿½ï¿½ÌƒIï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½ï¿½Tï¿½ï¿½
                    Collider2D[] colliders = Physics2D.OverlapCircleAll(transform.position, 10f);

                    foreach (Collider2D col in colliders)
                    {
                        //Debug.Log("Detected Object: " + col.gameObject.name);
                        if (col.gameObject.tag == TargetTag)
                        {
                            // ï¿½ÍˆÍ“ï¿½ï¿½ÌƒIï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½Ö‚ÌQï¿½Æ‚ï¿½ï¿½æ“¾
                            target = col.gameObject;
                            mode = Mode.Chase;
                            // ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½targetObjectï¿½ğ‘€ï¿½Å‚ï¿½ï¿½Ü‚ï¿½
                        }
                    }

                    break;

                case Mode.Chase:
                    chaseCoolTime = kchaseCoolTime;
                    Debug.Log("chase");

                    if (target != null) // targetï¿½ï¿½nullï¿½Å‚È‚ï¿½ï¿½ï¿½ï¿½Æ‚ï¿½ï¿½mï¿½F
                    {
                        direction_ = target.transform.position - transform.position;
                        direction_.Normalize();
                        // transform.position += new Vector3(direction_.x * 5, 0, 0) * Time.deltaTime;

                        if (distance <= 24.0f)
                        {
                            if (!onDanbol)
                            {
                                transform.position += new Vector3(direction_.x * 6.0f, 0, 0) * Time.deltaTime;
                            }
                            if (distance <= 7.0f)
                            {
                                mode = Mode.Hikkaku;
                            }
                        }
                        else
                        {
                            mode = Mode.Scan;
                        }

                    }
                    break;

                case Mode.Hikkaku:
                    Debug.Log("hikkaku");
                    FindClosestChild();
                    if (closestChild != null)
                    {
                        //lockOn = true;
                        //Debug.Log("tabetyaunyaaaaa");
                        //mode = Mode.Kuwaeru;
                    }
                    //else
                    //{
                    //    //lockOn = false;
                    //    //targetPos = player.transform.position;
                    //    // targetPos = Vector3.zero;
                    //    mode = Mode.Scan;

                    //}

                    //else
                    //{
                    //    mode = Mode.Scan;

                    //}
                    // target = null;
                    if (distance > 4.0f)
                    {
                        mode = Mode.Chase;
                    }

                    break;

                case Mode.Kuwaeru:
                    if (closestChild != null)
                    {
                        FindClosestChild();
                    }
                    if (kuwaeru && closestChild != null)
                    {
                        if (distance >= 7.0f)
                        {
                            mode = Mode.Scan;
                            kuwaeru = false;
                        }
                        if (direction_.x < 0)
                        {
                            closestChild.position = new Vector3(transform.position.x + 1.5f, transform.position.y - 1.0f, 0);
                        }
                        if (direction_.x >= 0)
                        {
                            closestChild.position = new Vector3(transform.position.x - 1.5f, transform.position.y - 1.0f, 0);
                        }
                        if (!onDanbol)
                        {
                            transform.position += new Vector3(direction_.x * -4.0f, 0, 0) * Time.deltaTime;
                            closestChild.position = transform.position;
                        }
                        BakuBakuTime -= Time.deltaTime;
                    }
                    else
                    {
                        Vector2 direction = target.transform.position - transform.position;
                        direction.Normalize();
                        if (direction.x > 0)
                        {
                            direction.x = 1.0f;
                        }
                        else
                        {
                            direction.x = -1.0f;
                        }
                        if (!onDanbol)
                        {
                            transform.position += new Vector3(direction.x * 2.0f, 0, 0) * Time.deltaTime;
                        }
                    }
                    //else
                    //{
                    //    mode = Mode.Scan;
                    //}
                    if (BakuBakuTime < 0)
                    {
                        mode = Mode.Scan;
                        kuwaeru = false;
                        //Destroy(closestChild.gameObject);
                    }
                    break;



            }


            Debug.Log(mode);

            // ï¿½ï¿½Ê“ï¿½ï¿½Éï¿½ï¿½ß‚ï¿½ï¿½ï¿½ï¿½ï¿½
            float thisLeft = transform.position.x - transform.localScale.x * 0.5f;
            float thisRight = transform.position.x + transform.localScale.x * 0.5f;
            float cameraLeft = scrollManager.GetScrollValue() - halfWidth;
            float cameraRight = scrollManager.GetScrollValue() + halfWidth;
            if (thisLeft < cameraLeft)
            {
                transform.position = new(cameraLeft + transform.localScale.x * 0.5f, transform.position.y, transform.position.z);
            }
            if (thisRight > cameraRight)
            {
                transform.position = new(cameraRight - transform.localScale.x * 0.5f, transform.position.y, transform.position.z);
            }
        }
        else
        {
            float thisRight = transform.position.x + transform.localScale.x * 0.5f;
            float cameraRight = scrollManager.GetScrollValue() + halfWidth;
            if (thisRight < cameraRight)
            {
                isEnterCamera = true;
            }
        }

        Animation();
    }
    private void FixedUpdate()
    {
        if (isAttack)
        {
            Vector2 forceDirection = direction_.normalized;
            //target.GetComponent<PlayerManager>().velocity = forceDirection;
            //target.transform.position = forceDirection;
        }
    }
    void EaseEndFanction()
    {
        mode = Mode.Hikkaku;
    }
    private void OnTriggerEnter2D(Collider2D collision)
    {
        if (collision.gameObject.CompareTag("Player")) // ï¿½vï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½[ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½Æ‚ÌÕ“Ë‚ï¿½ï¿½ï¿½ï¿½o
        {
            // Rigidbody2D rb = collision.gameObject.GetComponent<Rigidbody2D>();
            // isAttack = true;
            collision.GetComponent<PlayerManager>().SetSpeedDown();
            isAttack = true;
        }
        if (collision.CompareTag("Child") && mode == Mode.Kuwaeru)
        {
            //collision.transform.position = transform.position;
            kuwaeru = true;
            if (BakuBakuTime <= 0.2f)
            {
                Destroy(collision.gameObject);
                mode = Mode.Scan;
                kuwaeru = false;
                BakuBakuTime = kBakuBakuTime;
            }
        }
        if (collision.CompareTag("Obstacle"))
        {
            float x = collision.transform.position.x - transform.position.x;
            if (direction_.x > 0 && x > 0)
            {
                onDanbol = true;
            }
            else
            if (direction_.x < 0 && x < 0)
            {
                onDanbol = true;
            }
            else
            {
                onDanbol = false;
            }
        }
        if (collision.CompareTag("Player") && mode == Mode.Hikkaku)
        {
            Debug.Log("tabetyaunyaaaaa");
            mode = Mode.Kuwaeru;
            anim.SetTrigger("Attack");
        }
    }
    private void OnTriggerStay2D(Collider2D collision)
    {
        if (collision.CompareTag("Child") && mode == Mode.Kuwaeru)
        {
            //collision.transform.position = transform.position;
            kuwaeru = true;
            if (BakuBakuTime <= 0.2f)
            {
                Destroy(collision.gameObject);
                mode = Mode.Scan;
                kuwaeru = false;
                BakuBakuTime = kBakuBakuTime;
            }
        }
        if (collision.CompareTag("Player") && mode == Mode.Hikkaku)
        {
            Debug.Log("tabetyaunyaaaaa");
            mode = Mode.Kuwaeru;
            anim.SetTrigger("Attack");
        }
        if (collision.CompareTag("Obstacle"))
        {
            float x = collision.transform.position.x - transform.position.x;
            if (direction_.x > 0 && x > 0)
            {
                onDanbol = true;
            }
            else
            if (direction_.x < 0 && x < 0)
            {
                onDanbol = true;
            }
            else
            {
                onDanbol = false;
            }
        }
    }
    private void OnTriggerExit2D(Collider2D collision)
    {
        if (collision.gameObject.CompareTag("Player")) // ï¿½vï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½[ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½Æ‚ÌÕ“Ë‚ï¿½ï¿½ï¿½ï¿½o
        {
            // Rigidbody2D rb = collision.gameObject.GetComponent<Rigidbody2D>();
            isAttack = false;
        }
        if (collision.CompareTag("Obstacle"))
        {
            //mode = Mode.Scan;
            onDanbol = false;
            // Debug.Log("danbo-ru");
        }
    }

    public void rockFlipTrue()
    {

        canFlip = true;
    }

    public void rockFlipFalse()
    {

        canFlip = false;
    }

    void Animation()
    {

        bool isScan = false;
        bool isAttack = false;

        switch (mode)
        {
            case Mode.Scan:
                isScan = true;
                break;
            case Mode.Chase:

                break;

            case Mode.Hikkaku:
                isAttack = true;
                break;

            case Mode.Kuwaeru:

                break;
        }

        anim.SetBool("isScan", isScan);
        anim.SetBool("isAttack", isAttack);

        if (canFlip == true)
        {
            if (this.transform.position.x < prePos.x)
            {
                spriteRenderer.flipX = false;
            }
            else if (this.transform.position.x > prePos.x)
            {
                spriteRenderer.flipX = true;
            }
        }

        prePos = this.transform.position;
    }
    void FindClosestChild()
    {
        GameObject[] children = GameObject.FindGameObjectsWithTag("Child");

        float closestDistance = float.MaxValue;

        foreach (GameObject child in children)
        {
            float distanceToChild = Vector3.Distance(transform.position, child.transform.position);

            if (distanceToChild < closestDistance)
            {
                closestDistance = distanceToChild;
                closestChild = child.transform;
            }
        }



    }
}
